# 1. Tensor

>**Tensor**는 **Array나 Matrix와 유사한 자료구조**다.  
pytorch에서 tensor를 사용하여 **Model의 Input과 Output, 그리고 Model의 Parameter들을 Encode한다.**

>tensor는 **GPU나 다른 H/W 가속기에서 실행할 수 있다는 점을 제외하면 Numpy의 ndarray와 유사하다.**  
실제로 tensor와 **Numpy의 array는 종종 동일한 Underly 메모리를 공유할 수 있어 데이터를 복사할 필요가 없다.**

>tensor는 **Automatic Differentiation에 최적화되어 있다.**

In [1]:
import torch
import numpy as np

## Initializing a Tensor

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [4]:
x_ones = torch.ones_like(x_data) # x_data의 속성은 유지하면서 1로 채우기
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성은 유지하면서 랜덤한 float으로 채우기
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1476, 0.6100],
        [0.6321, 0.6000]])


In [5]:
shape = (2, 3,) # 2 × 3 크기의 shape을 설정하고
rand_tensor = torch.rand(shape) # 그 모양으로 tensor 만들기
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7909, 0.0993, 0.4865],
        [0.1693, 0.4122, 0.1775]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attribute of a Tensor

In [6]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}') # tensor의 shape
print(f'Datatype of tensor: {tensor.dtype}') # tensor의 datatype
print(f'Device tensor is stored on: {tensor.device}') # tensor가 어디에 저장되는지

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

100가지 이상의 **Tensor Operations**  
<https://pytorch.org/docs/stable/torch.html>

>각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있다.  
기본적으로 tensor는 CPU에 생성되는데, ```.to``` method를 사용하면  
(GPU의 가용성(availability)을 확인한 뒤) GPU로 tensor를 명시적으로 이동할 수 있다.

>*장치들 간에 큰 tensor를 복사하는 것은 시간과 메모리 측면에서 비용이 많이듬에 주의*

In [7]:
# GPU가 존재하면 Tensor를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


In [8]:
tensor = torch.ones(4, 4)
print(f'Fisrt row: {tensor[0]}')
print(f'Fisrt column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')
tensor[:, 1] = 0
print(tensor)

Fisrt row: tensor([1., 1., 1., 1.])
Fisrt column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# 두 tensor의 Matrix Multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# y1, y2, y3 모두 같은 연산을 한거임
print(f'tensor:\n {tensor}')
print(f'tesnor.T:\n {tensor.T}')
print(f'y1:\n {y1}')
print(f'y2:\n {y2}')
print(f'y3:\n {y3}')

# 두 tensor의 Element-wise product (Hadamard product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# z1, z2, z3 모두 같은 연산을 한거임
print(f'z1:\n {z1}')
print(f'z2:\n {z2}')
print(f'z3:\n {z3}')

tensor:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tesnor.T:
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y1:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
agg = tensor.sum() # tensor의 모든 요소들의 합
agg_item = agg.item() # agg를 Python의 숫자로 형변환
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


In [12]:
print(f'{tensor} \n')
tensor.add_(5) # in-place 연산으로, 연산 결과를 피연산자에 저장한다. '_' 접미사를 갖는다.
print(tensor)
# in-place 연산은 메모리를 일부 절약하지만, history가 즉시 삭제되어 derivative 계산에 문제가 발생할 수 있다.
# 따라서 사용을 권장하지 않는다.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Brigde with Numpy

>CPU 상의 tensor와 Numpy array는 메모리 공간을 공유하기 때문에  
하나를 변경하면 다른 하나도 변경된다.

In [13]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
